name = "caro-server"
main = "src/index.js"
compatibility_date = "2024-05-12"

[vars]
# Restrict to your frontend origin in production.
# GitHub Pages domain for tungtt2203.
ALLOWED_ORIGIN = "https://ninetysixxx.github.io"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]
